config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials: 
      - id: iisas_openstack_url
        variable: OPENSTACK_URL
      - id: mswss_token
        variable: MSWSS_TOKEN
        

sqa_criteria:
  SvcQC.Dep:
    repos:
      im:
        container: imclient
        commands:
          - |
            #!/bin/sh
            printf "$(cat /im/auth/auth.dat)" "${MSWSS_TOKEN}" iisas "${OPENSTACK_URL}" "egi.eu" "${MSWSS_TOKEN}" "openid" "eosc-synergy.eu" > ${IM_AUTH_FILE}
            im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" create_wait_outputs /IM/mswss-infrastructure-static.radl > mswss_im.json
            RETURN_CODE=$?
            echo "im_client.py create_wait_outputs return code: ${RETURN_CODE}"
            echo "Infrastructure Manager output:"
            cat ./mswss_im.json
            if [ ${RETURN_CODE} -eq 0 ]; then
              INFID=$(jq -r '[ .infid ] | .[]' ./mswss_im.json)
              echo "INFID=${INFID}"
              im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" destroy ${INFID}
              echo "im_client.py destroy return code: $?"
            else
              exit ${RETURN_CODE}
            fi



environment:
  IM_AUTH_FILE: "/im/auth.dat"
  #JPL_DOCKERPUSH: "kubectl"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: 45

  timeout: 3600
