config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials: 
      - id: iisas_openstack_url
        variable: OPENSTACK_URL
      - id: mswss_token
        variable: MSWSS_TOKEN
        

sqa_criteria:
  SvcQC.Dep:
    repos:
      im:
        container: imclient
        commands:
          - |
            #!/bin/sh
            printf "$(cat /im/auth/auth.dat)" "${MSWSS_TOKEN}" iisas "${OPENSTACK_URL}" "egi.eu" "${MSWSS_TOKEN}" "openid" "eosc-synergy.eu" > ${IM_AUTH_FILE}
            out=$(im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" create /IM/mswss-infrastructure-static.radl)
            RETURN_CODE=$?
            echo "im_client.py create return code: ${RETURN_CODE}"
            echo "Infrastructure Manager output:"
            echo $out
            if [ ${RETURN_CODE} -eq 0 ]; then
              INFID=${out/* /}
              echo "INFID=${INFID}"
              echo ${INFID} > infid
              im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" wait ${INFID}
              RETURN_CODE=$?
              echo "im_client.py wait return code: ${RETURN_CODE}"
              echo "Status of the infrastructure ${INFID}:"
              im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" getstate ${INFID}
              if [ ${RETURN_CODE} -eq 1 ]; then
                  im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" getcontmsg ${INFID}
              fi
            fi
            exit ${RETURN_CODE}
          - |
            #!/bin/sh
            if [ ! -f infid ] ; then
              exit 1
            fi
            INFID=$(cat infid)
            echo "Customising infrastructure ${INFID}"
            ssh_cmd=$(im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" sshvm ${INFID} 0 1 | tail -1)
            echo "SSH command: ${ssh_cmd}"
            apk add openssh
            $ssh_cmd 'bash -c "git clone https://github.com/MSWSS-EOSC/deployment"'
            RETURN_CODE=$?
            if [ ${RETURN_CODE} -eq 0 ]; then
              $ssh_cmd 'bash ./deployment/scripts/mswss_galaxy_customise.sh'
              RETURN_CODE=$?
            fi
            echo "Destroying infrastructure ${INFID}"
            im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" destroy ${INFID}
            
            echo "Return code: ${RETURN_CODE}"
            #exit ${RETURN_CODE}
            
            



environment:
  IM_AUTH_FILE: "/im/auth.dat"
  #JPL_DOCKERPUSH: "kubectl"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: 45

timeout: 3600
