config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials: 
      - id: iisas_openstack_url
        variable: OPENSTACK_URL
      - id: mswss_token
        variable: MSWSS_TOKEN
        

sqa_criteria:
  SvcQC.Dep:
    repos:
      im:
        container: imclient
        commands:
          - |
            #!/bin/sh
            printf "$(cat /im/auth/auth.dat)" "${MSWSS_TOKEN}" iisas "${OPENSTACK_URL}" "egi.eu" "${MSWSS_TOKEN}" "openid" "eosc-synergy.eu" > ${IM_AUTH_FILE}
            out=$(im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" create /IM/mswss-infrastructure-static.radl)
            RETURN_CODE=$?
            echo "im_client.py create return code: ${RETURN_CODE}"
            echo "Infrastructure Manager output:"
            echo $out
            if [ ${RETURN_CODE} -eq 0 ]; then
              INFID=${out/* /}
              echo "INFID=${INFID}"
              im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" wait ${INFID}
              RETURN_CODE=$?
              echo "im_client.py wait return code: ${RETURN_CODE}"
              echo "destroying infrastructure ${INFID}"
              im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" destroy ${INFID}
            fi
            exit ${RETURN_CODE}
            



environment:
  IM_AUTH_FILE: "/im/auth.dat"
  #JPL_DOCKERPUSH: "kubectl"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: 45

timeout: 3600
