config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa/docker-compose.yml'
  credentials:
      - id: ifca_openstack
        variable: OPENSTACK_URL
      - id: ifca_openstack_id
        username_var: OPENSTACK_USER
        password_var: OPENSTACK_PASS
      - id: upv_im_id
        username_var: IM_USER
        password_var: IM_PASS
      #- id: mswss_auth_dat
      #  variable: IM_AUTH_FILE

sqa_criteria:
  SvcQC.Dep:
    repos:
      im:
        container: imclient
        commands:
          - |
            #!/bin/bash
            printf "$(cat /im/auth/auth.dat)" "${IM_USER}" "${IM_PASS}" ifca "${OPENSTACK_URL}" "${OPENSTACK_USER}" "${OPENSTACK_PASS}" "VO:eosc-synergy.eu" "IFCA local users" > ${IM_AUTH_FILE}
            # Temporarily disabled for the testing of Jenkins
            im_client.py -r https://appsgrycap.i3m.upv.es:31443/im/ -a "${IM_AUTH_FILE}" create_wait_outputs /IM/mswss-infrastructure-static.radl > mswss_im.json
            echo "im_client.py create_wait_outputs return code: $?"
            INFID=$(jq '[ .infid ]'  ./mswss_im.json)
            im_client.py -a "${IM_AUTH_FILE}" destroy ${INFID}
            echo "im_client.py destroy return code: $?"

environment:
  IM_AUTH_FILE: "/im/auth.dat"
  #JPL_DOCKERPUSH: "kubectl"
  #JPL_IGNOREFAILURES: "defined"
  #JPL_DOCKERFORCEBUILD: "enabled"
  #JPL_WORKSPACEDEBUG: "true"
  #JPL_WORKSPACEDEBUGTIMEOUT: 45

#timeout: 1200
