version: "3.7"

services:
  imclient:
    environment:
     - IM_AUTH_FILE
    image: "eoscsynergy/im-client:1.5.9"
    container_name: "imclient"
    hostname: "imclient"
    volumes:
     - ./IM:/IM
     - ./auth:/im/auth
    entrypoint: [/bin/sleep, infinity]
